import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Footer from "./components/footer";
import ToastProvider from "./components/ToastProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased min-h-screen flex flex-col`}
      >
        <div className="flex flex-col min-h-screen flex-1">
          <main className="flex-1">{children}</main>
          <Footer />
          <ToastProvider />
        </div>
      </body>
    </html>
  );
}
